Bulky/Areas/Admin/Controllers/CategoryController.cs
using Bulky.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace Bulky.Controllers;

public class CategoryController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public CategoryController(IUnitOfWork unitOfWork) => _unitOfWork = unitOfWork;

    public IActionResult Index()
    {
        return View(_unitOfWork.CategoryRepository.GetAll());
    }

    public IActionResult Create() => View();

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Category category)
    {
        if (category.Name == category.DisplayOrder.ToString())
            ModelState.AddModelError("name", "Category & DisplayOrder Can't be the same");
        if (!ModelState.IsValid) return View();
        _unitOfWork.CategoryRepository.Add(category);
        _unitOfWork.Save();
        TempData["success"] = "Category Created Successfully";
        return RedirectToAction("Index");
    }

    public IActionResult Edit(int? id)
    {
        var category = _unitOfWork.CategoryRepository.GetFirstOrDefault(u => u.Id == id);
        return View(category);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Category category)
    {
        if (category.Name == category.DisplayOrder.ToString())
            ModelState.AddModelError("name", "Category & DisplayOrder Can't be the same");
        if (!ModelState.IsValid) return View();
        _unitOfWork.CategoryRepository.Update(category);
        _unitOfWork.Save();
        TempData["success"] = "Category Updated Successfully";
        return RedirectToAction("Index");
    }


    public IActionResult Delete(int? id)
    {
        var category = _unitOfWork.CategoryRepository.GetFirstOrDefault(u => u.Id == id);
        return View(category);
    }

    [HttpPost]
    public IActionResult Delete(Category category)
    {
        _unitOfWork.CategoryRepository.Remove(category);
        _unitOfWork.Save();
        TempData["success"] = "Category Deleted Successfully";
        return RedirectToAction("Index");
    }

}

Bulky/Areas/Admin/Controllers/CoverTypeController.cs
using Bulky.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace Bulky.Controllers;
public class CoverTypeController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public CoverTypeController(IUnitOfWork unitOfWork) => _unitOfWork = unitOfWork;

    public IActionResult Index() => View(_unitOfWork.CoverTypeRepository.GetAll());

    public IActionResult Create() => View();

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(CoverType coverType)
    {
        if (!ModelState.IsValid) return View();
        _unitOfWork.CoverTypeRepository.Add(coverType);
        _unitOfWork.Save();
        TempData["success"] = "Cover Type Create Successfully";
        return RedirectToAction("Index");
    }

    public IActionResult Edit(int? id) => View(_unitOfWork.CoverTypeRepository.GetFirstOrDefault(coverType => coverType.Id == id));

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(CoverType coverType)
    {
        if (!ModelState.IsValid) return View();
        _unitOfWork.CoverTypeRepository.Update(coverType);
        _unitOfWork.Save();
        return RedirectToAction("Index");
    }

    public IActionResult Delete(int? id) => View(_unitOfWork.CoverTypeRepository.GetFirstOrDefault(coverType => coverType.Id == id));

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete(CoverType coverType)
    {
        _unitOfWork.CoverTypeRepository.Remove(coverType);
        _unitOfWork.Save();
        return RedirectToAction("Index");
    }

}

Bulky/Areas/Customer/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;

namespace Bulky.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Bulky/Areas/Admin/Views/Category/Create.cshtml
@model Category


<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pd-2">
            <h2 class="text-primary">Create Category</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control">
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div>
        <button class="btn btn-success" type="submit">
            Create
        </button>
        <a class="btn btn-secondary" type="button" asp-controller="Category" asp-action="Index">
            Back To List
        </a>
    </div>
</form>


@section Scripts
{
@{
<partial name="_ValidationScriptsPartial" />
}
}

Bulky/Areas/Admin/Views/Category/Delete.cshtml
@model Category


<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pd-2">
            <h2 class="text-primary">Delete Category</h2>
            <hr/>
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" disabled="disabled" value="@Model.Name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control" disabled="disabled" value="@Model.DisplayOrder">
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div>
        <button class="btn btn-danger" type="submit">
            Delete
        </button>
        <a class="btn btn-secondary" type="button" asp-controller="Category" asp-action="Index">
            Back To List
        </a>
    </div>
</form>


@section Scripts
{
@{
<partial name="_ValidationScriptsPartial" />
}
}

Bulky/Areas/Admin/Views/Category/Edit.cshtml
@model Category


<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pd-2">
            <h2 class="text-primary">Edit Category</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" value="@Model.Name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control" value="@Model.DisplayOrder">
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div>
        <button class="btn btn-success" type="submit">
            Update
        </button>
        <a class="btn btn-secondary" type="button" asp-controller="Category" asp-action="Index">
            Back To List
        </a>
    </div>
</form>


@section Scripts
{
@{
<partial name="_ValidationScriptsPartial" />
}
}

Bulky/Areas/Admin/Views/Category/Index.cshtml
@model IEnumerable<Category>
@{
    ViewData["Title"] = "Category Page";
}
<h1>Index Category</h1>
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Category List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Category" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create new Category
            </a>
        </div>
    </div>
</div>
<br>

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>Category Name</th>
            <th>Display Order</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var category in Model)
        {
            <tr>
                <td>@category.Name</td>
                <td width="30%">@category.DisplayOrder</td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Category" asp-action="Edit" asp-route-id="@category.Id"
                           class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                        <a asp-controller="Category" asp-action="Delete" asp-route-id="@category.Id"
                           class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

Bulky/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType


<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pd-2">
            <h2 class="text-primary">Create CoverType</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button class="btn btn-success" type="submit">
            Create
        </button>
        <a class="btn btn-secondary" type="button" asp-controller="CoverType" asp-action="Index">
            Back To List
        </a>
    </div>
</form>


@section Scripts
{
@{
<partial name="_ValidationScriptsPartial" />
}
}

Bulky/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverType


<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pd-2">
            <h2 class="text-primary">Delete CoverType</h2>
            <hr/>
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" disabled="disabled" value="@Model.Name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button class="btn btn-danger" type="submit">
            Delete
        </button>
        <a class="btn btn-secondary" type="button" asp-controller="CoverType" asp-action="Index">
            Back To List
        </a>
    </div>
</form>


@section Scripts
{
@{
<partial name="_ValidationScriptsPartial" />
}
}

Bulky/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType


<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pd-2">
            <h2 class="text-primary">Edit CoverType</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" value="@Model.Name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button class="btn btn-success" type="submit">
            Update
        </button>
        <a class="btn btn-secondary" type="button" asp-controller="CoverType" asp-action="Index">
            Back To List
        </a>
    </div>
</form>


@section Scripts
{
@{
<partial name="_ValidationScriptsPartial" />
}
}

Bulky/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverType>
@{
    ViewData["Title"] = "Cover Type Page";
}
<h1>Index Category</h1>
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">CoverType List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="CoverType" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create new CoverType
            </a>
        </div>
    </div>
</div>
<br>

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>Cover Id</th>
            <th>Cover Name</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var coverType in Model)
        {
            <tr>
                <td>@coverType.Id</td>
                <td>@coverType.Name</td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a 
                            asp-controller="CoverType" 
                            asp-action="Edit" 
                            asp-route-id="@coverType.Id"
                            class="btn btn-primary mx-2"
                        >
                             <i class="bi bi-pencil-square"></i> Edit
                        </a>
                        <a
                            asp-controller="CoverType"
                            asp-action="Delete"
                            asp-route-id="@coverType.Id"
                            class="btn btn-danger mx-2"
                        >
                             <i class="bi bi-trash-fill"></i> Delete
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

Bulky/Areas/Customer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Ayman Kheireldeen This is me Mohamed</h1>
    <button class="btn-primary">New Button</button>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Bulky/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bulky</title>
    <link rel="stylesheet" href="~/css/bootsWatchTheme.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bulky.styles.css" asp-append-version="true" />
    
  
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="index">Bulky Book</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02"
                    aria-controls="navbarColor02" aria-expanded="true" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse show" id="navbarColor02" style="">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Type</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification"/>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container">
            &copy; 2022 - Bulky - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Bulky/Views/Shared/_Notification.cshtml
@if(TempData["Success"] != null) 
{  
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]');
    </script>
}

@if(TempData["Error"] != null) 
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}